/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProvenanceAnchorRegistry } from "./ProvenanceAnchorRegistry";
export * as factories from "./factories";
export { ProvenanceAnchorRegistry__factory } from "./factories/ProvenanceAnchorRegistry__factory";
