/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProvenanceAnchorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchors"
      | "hashRegistered"
      | "registerAnchor"
      | "verifyHash"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProvenanceAnchored"): EventFragment;

  encodeFunctionData(functionFragment: "anchors", values: [string]): string;
  encodeFunctionData(
    functionFragment: "hashRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAnchor",
    values: [string, BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHash",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "anchors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAnchor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
}

export namespace ProvenanceAnchoredEvent {
  export type InputTuple = [
    artifactId: string,
    contentHash: BytesLike,
    hcsSequenceNumber: BigNumberish,
    timestamp: BigNumberish,
    registrar: AddressLike
  ];
  export type OutputTuple = [
    artifactId: string,
    contentHash: string,
    hcsSequenceNumber: bigint,
    timestamp: bigint,
    registrar: string
  ];
  export interface OutputObject {
    artifactId: string;
    contentHash: string;
    hcsSequenceNumber: bigint;
    timestamp: bigint;
    registrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProvenanceAnchorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProvenanceAnchorRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProvenanceAnchorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchors: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, string] & {
        contentHash: string;
        artifactId: string;
        artifactType: string;
        hcsSequenceNumber: bigint;
        timestamp: bigint;
        registrar: string;
      }
    ],
    "view"
  >;

  hashRegistered: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  registerAnchor: TypedContractMethod<
    [
      artifactId: string,
      contentHash: BytesLike,
      artifactType: string,
      hcsSequenceNumber: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  verifyHash: TypedContractMethod<
    [artifactId: string, testHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchors"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, string] & {
        contentHash: string;
        artifactId: string;
        artifactType: string;
        hcsSequenceNumber: bigint;
        timestamp: bigint;
        registrar: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashRegistered"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerAnchor"
  ): TypedContractMethod<
    [
      artifactId: string,
      contentHash: BytesLike,
      artifactType: string,
      hcsSequenceNumber: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [artifactId: string, testHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ProvenanceAnchored"
  ): TypedContractEvent<
    ProvenanceAnchoredEvent.InputTuple,
    ProvenanceAnchoredEvent.OutputTuple,
    ProvenanceAnchoredEvent.OutputObject
  >;

  filters: {
    "ProvenanceAnchored(string,bytes32,uint64,uint256,address)": TypedContractEvent<
      ProvenanceAnchoredEvent.InputTuple,
      ProvenanceAnchoredEvent.OutputTuple,
      ProvenanceAnchoredEvent.OutputObject
    >;
    ProvenanceAnchored: TypedContractEvent<
      ProvenanceAnchoredEvent.InputTuple,
      ProvenanceAnchoredEvent.OutputTuple,
      ProvenanceAnchoredEvent.OutputObject
    >;
  };
}
