{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "88ea52f2",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-07-31T01:32:26.674259Z",
     "iopub.status.busy": "2026-07-31T01:32:26.673892Z",
     "iopub.status.idle": "2026-07-31T01:32:30.798503Z",
     "shell.execute_reply": "2026-07-31T01:32:30.797358Z"
    },
    "papermill": {
     "duration": 4.131122,
     "end_time": "2026-07-31T01:32:30.800515+00:00",
     "exception": false,
     "start_time": "2026-07-31T01:32:26.669393+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "===========================================================================\n",
      "DR. T CLINICAL NLP & PATIENT HEART COMPANION - OFFLINE KAGGLE PIPELINE\n",
      "Target Notebook: https://www.kaggle.com/code/zenieverse/notebookc05162cafa/edit\n",
      "===========================================================================\n",
      "[+] PyTorch Version: 2.10.0+cpu\n",
      "[+] CUDA Available: False\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import re\n",
    "import json\n",
    "import time\n",
    "import math\n",
    "import random\n",
    "import datetime\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "print(\"=\" * 75)\n",
    "print(\"DR. T CLINICAL NLP & PATIENT HEART COMPANION - OFFLINE KAGGLE PIPELINE\")\n",
    "print(\"Target Notebook: https://www.kaggle.com/code/zenieverse/notebookc05162cafa/edit\")\n",
    "print(\"=\" * 75)\n",
    "\n",
    "# Check PyTorch & CUDA Availability for Offline Acceleration\n",
    "try:\n",
    "    import torch\n",
    "    print(f\"[+] PyTorch Version: {torch.__version__}\")\n",
    "    print(f\"[+] CUDA Available: {torch.cuda.is_available()}\")\n",
    "    if torch.cuda.is_available():\n",
    "        print(f\"[+] Device Name: {torch.cuda.get_device_name(0)}\")\n",
    "    device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "except ImportError:\n",
    "    print(\"[!] PyTorch not found in environment. Running in CPU NumPy fallback mode.\")\n",
    "    device = \"cpu\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d1bb7762",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-07-31T01:32:30.807868Z",
     "iopub.status.busy": "2026-07-31T01:32:30.807013Z",
     "iopub.status.idle": "2026-07-31T01:32:30.816387Z",
     "shell.execute_reply": "2026-07-31T01:32:30.815191Z"
    },
    "papermill": {
     "duration": 0.015448,
     "end_time": "2026-07-31T01:32:30.818518+00:00",
     "exception": false,
     "start_time": "2026-07-31T01:32:30.803070+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[+] HIPAA/GDPR Anonymizer initialized successfully.\n"
     ]
    }
   ],
   "source": [
    "class HIPAAAnonymizer:\n",
    "    \"\"\"\n",
    "    De-identifies Patient Health Information (PHI) and Personally Identifiable\n",
    "    Information (PII) for secure R&D clinical repository archiving.\n",
    "    \"\"\"\n",
    "    def __init__(self):\n",
    "        self.patterns = {\n",
    "            'email': r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}',\n",
    "            'phone': r'\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}',\n",
    "            'ssn': r'\\b\\d{3}-\\d{2}-\\d{4}\\b',\n",
    "            'mrn': r'\\bMRN[-:\\s]?\\d{6,10}\\b|\\bID[-:\\s]?\\d{6,10}\\b',\n",
    "            'date': r'\\b\\d{1,2}[/-]\\d{1,2}[/-]\\d{2,4}\\b|\\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \\d{1,2},? \\d{4}\\b',\n",
    "            'doctor': r'\\bDr\\.\\s+[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)?\\b',\n",
    "            'location': r'\\b(?:Hospital|Clinic|Medical Center|Ward|ICU|Room)\\s+\\d+[A-Za-z]?\\b'\n",
    "        }\n",
    "\n",
    "    def anonymize(self, text, patient_id_seq=1001):\n",
    "        sanitized = text\n",
    "        sanitized = re.sub(self.patterns['email'], '[ANONYMIZED_EMAIL]', sanitized)\n",
    "        sanitized = re.sub(self.patterns['phone'], '[ANONYMIZED_PHONE]', sanitized)\n",
    "        sanitized = re.sub(self.patterns['ssn'], '[ANONYMIZED_SSN]', sanitized)\n",
    "        sanitized = re.sub(self.patterns['mrn'], '[ANONYMIZED_MRN]', sanitized)\n",
    "        sanitized = re.sub(self.patterns['date'], '[ANONYMIZED_DATE]', sanitized)\n",
    "        sanitized = re.sub(self.patterns['doctor'], '[ANONYMIZED_PHYSICIAN]', sanitized)\n",
    "        sanitized = re.sub(self.patterns['location'], '[ANONYMIZED_FACILITY]', sanitized)\n",
    "        \n",
    "        alias = f\"PATIENT_ANON_{patient_id_seq}\"\n",
    "        return sanitized, alias\n",
    "\n",
    "anonymizer = HIPAAAnonymizer()\n",
    "print(\"[+] HIPAA/GDPR Anonymizer initialized successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "13dde2cd",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-07-31T01:32:30.825439Z",
     "iopub.status.busy": "2026-07-31T01:32:30.824915Z",
     "iopub.status.idle": "2026-07-31T01:32:30.837843Z",
     "shell.execute_reply": "2026-07-31T01:32:30.836827Z"
    },
    "papermill": {
     "duration": 0.018669,
     "end_time": "2026-07-31T01:32:30.839630+00:00",
     "exception": false,
     "start_time": "2026-07-31T01:32:30.820961+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[+] Clinical NLP Extractor loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "class ClinicalNLPExtractor:\n",
    "    \"\"\"\n",
    "    Offline Rule & Keyword/Embedding NLP Extractor for Patient Heart Narratives.\n",
    "    Detects Emotional States, Physical Symptoms, Pain Scales, and R&D Takeaways.\n",
    "    \"\"\"\n",
    "    EMOTION_DICTIONARY = {\n",
    "        'Anxiety & Fear': ['anxious', 'terrified', 'scared', 'fear', 'panic', 'dread', 'worried', 'nervous', 'scared of needles', 'afraid'],\n",
    "        'Exhaustion & Fatigue': ['exhausted', 'tired', 'drained', 'fatigue', 'weakness', 'no energy', 'burnout', 'heavy'],\n",
    "        'Physical Pain & Discomfort': ['pain', 'hurt', 'aching', 'cramps', 'throbbing', 'sore', 'burning', 'sharp pain', 'stabbing'],\n",
    "        'Emotional Isolation & Sadness': ['lonely', 'isolated', 'crying', 'sad', 'depressed', 'hopeless', 'overwhelmed', 'no one understands'],\n",
    "        'Hope & Resilience': ['hopeful', 'trying', 'determined', 'better today', 'thankful', 'fighting', 'grateful', 'optimistic'],\n",
    "        'Nausea & Side Effects': ['nausea', 'vomiting', 'sick to stomach', 'queasy', 'dizzy', 'loss of appetite', 'metallic taste']\n",
    "    }\n",
    "\n",
    "    SYMPTOM_DICTIONARY = {\n",
    "        'Needle Phobia / Vein Fragility': ['needle', 'vein', 'iv', 'phlebotomy', 'puncture', 'bruising'],\n",
    "        'Chemo / Infusion Nausea': ['nausea', 'infusion', 'chemo', 'drip', 'vomit', 'appetite'],\n",
    "        'Insomnia & Sleep Disturbance': ['insomnia', 'cannot sleep', 'awake all night', 'restless'],\n",
    "        'Pagophagia / Pica': ['ice', 'chewing ice', 'ice craving', 'crunching ice'],\n",
    "        'Cardiovascular Palpitations': ['heart racing', 'palpitations', 'fluttering', 'chest tightness', 'short of breath'],\n",
    "        'Neuropathy / Tingling': ['tingling', 'numbness', 'pins and needles', 'fingertips']\n",
    "    }\n",
    "\n",
    "    def analyze(self, text):\n",
    "        text_lower = text.lower()\n",
    "        \n",
    "        # 1. Detected Emotions\n",
    "        detected_emotions = []\n",
    "        for emotion, keywords in self.EMOTION_DICTIONARY.items():\n",
    "            if any(kw in text_lower for kw in keywords):\n",
    "                detected_emotions.append(emotion)\n",
    "        if not detected_emotions:\n",
    "            detected_emotions = ['General Vulnerability / Emotional Stress']\n",
    "\n",
    "        # 2. Detected Symptoms\n",
    "        detected_symptoms = []\n",
    "        for symptom, keywords in self.SYMPTOM_DICTIONARY.items():\n",
    "            if any(kw in text_lower for kw in keywords):\n",
    "                detected_symptoms.append(symptom)\n",
    "        if not detected_symptoms:\n",
    "            detected_symptoms = ['General Treatment Fatigue / Malaise']\n",
    "\n",
    "        # 3. R&D Clinical Recommendations\n",
    "        rnd_takeaways = []\n",
    "        if 'Needle Phobia / Vein Fragility' in detected_symptoms:\n",
    "            rnd_takeaways.append(\"R&D Medical Device Rec: Implement vein-visualization IR scanner & micro-needle infusion ports to lower phlebotomy trauma.\")\n",
    "        if 'Chemo / Infusion Nausea' in detected_symptoms:\n",
    "            rnd_takeaways.append(\"R&D Pharma Rec: Formulate fast-acting sublingual anti-emetic strips prior to infusion cycles.\")\n",
    "        if 'Pagophagia / Pica' in detected_symptoms:\n",
    "            rnd_takeaways.append(\"R&D Diagnostics Rec: Pagophagia is a strong biomarker for severe iron deficiency anemia; trigger automated ferritin lab panels.\")\n",
    "        if not rnd_takeaways:\n",
    "            rnd_takeaways.append(\"R&D Care Quality Rec: Enhance patient-centered empathetic check-ins and provide personalized recovery schedules.\")\n",
    "\n",
    "        # 4. Phase Categorization\n",
    "        phase = \"Pre-Treatment / Prep\"\n",
    "        if any(k in text_lower for k in ['during', 'chemo', 'infusion', 'active', 'daily dose', 'side effect']):\n",
    "            phase = \"Mid-Treatment / Active Care\"\n",
    "        elif any(k in text_lower for k in ['after', 'finished', 'post', 'remission', 'recovery', 'weeks later']):\n",
    "            phase = \"Post-Treatment / Recovery\"\n",
    "\n",
    "        return {\n",
    "            'emotions': detected_emotions,\n",
    "            'symptoms': detected_symptoms,\n",
    "            'rnd_recommendations': \" | \".join(rnd_takeaways),\n",
    "            'phase': phase\n",
    "        }\n",
    "\n",
    "extractor = ClinicalNLPExtractor()\n",
    "print(\"[+] Clinical NLP Extractor loaded successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "c7398e84",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-07-31T01:32:30.846675Z",
     "iopub.status.busy": "2026-07-31T01:32:30.846354Z",
     "iopub.status.idle": "2026-07-31T01:32:30.868311Z",
     "shell.execute_reply": "2026-07-31T01:32:30.867294Z"
    },
    "jupyter": {
     "source_hidden": true
    },
    "papermill": {
     "duration": 0.027696,
     "end_time": "2026-07-31T01:32:30.870130+00:00",
     "exception": false,
     "start_time": "2026-07-31T01:32:30.842434+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "# -*- coding: utf-8 -*-\n",
    "\"\"\"\n",
    "@license: SPDX-License-Identifier: Apache-2.0\n",
    "@description: Standalone pure deterministic symbolic operator library for ARC-AGI grids.\n",
    "\"\"\"\n",
    "\n",
    "def clone_grid(grid):\n",
    "    return [row[:] for row in grid]\n",
    "\n",
    "def apply_gravity(grid, anchor_color=2):\n",
    "    \"\"\"\n",
    "    Simulates downward gravity with diagonal anchor-support physics.\n",
    "    \"\"\"\n",
    "    R = len(grid)\n",
    "    C = len(grid[0])\n",
    "    result = clone_grid(grid)\n",
    "    \n",
    "    changed = True\n",
    "    while changed:\n",
    "        changed = False\n",
    "        for r in range(R - 2, -1, -1):\n",
    "            for c in range(C):\n",
    "                val = result[r][c]\n",
    "                if val == 1:\n",
    "                    blocked = result[r + 1][c] != 0\n",
    "                    \n",
    "                    if r + 1 < R:\n",
    "                        if c - 1 >= 0 and result[r + 1][c - 1] == anchor_color:\n",
    "                            blocked = True\n",
    "                        if c + 1 < C and result[r + 1][c + 1] == anchor_color:\n",
    "                            blocked = True\n",
    "                    \n",
    "                    if not blocked:\n",
    "                        result[r + 1][c] = 1\n",
    "                        result[r][c] = 0\n",
    "                        changed = True\n",
    "\n",
    "    for r in range(R):\n",
    "        for c in range(C):\n",
    "            if result[r][c] == anchor_color:\n",
    "                if r - 1 >= 0 and result[r - 1][c] == 1:\n",
    "                    result[r - 1][c] = 0\n",
    "                    result[r][c] = 3\n",
    "                \n",
    "                diagonal_offsets = [\n",
    "                    (-1, -1), (-1, 1), (1, -1), (1, 1), (0, -1), (0, 1)\n",
    "                ]\n",
    "                \n",
    "                has_diagonal_touch = False\n",
    "                for dr, dc in diagonal_offsets:\n",
    "                    nr = r + dr\n",
    "                    nc = c + dc\n",
    "                    if 0 <= nr < R and 0 <= nc < C:\n",
    "                        if result[nr][nc] == 1:\n",
    "                            has_diagonal_touch = True\n",
    "                \n",
    "                if has_diagonal_touch:\n",
    "                    result[r][c] = 3\n",
    "\n",
    "    return result\n",
    "\n",
    "def mirror_pivot(grid, pivot_color=4):\n",
    "    \"\"\"\n",
    "    Mirror grids horizontally across a colored anchor axis.\n",
    "    \"\"\"\n",
    "    result = clone_grid(grid)\n",
    "    R = len(result)\n",
    "    C = len(result[0])\n",
    "\n",
    "    pivot_c = -1\n",
    "    for r in range(R):\n",
    "        for c in range(C):\n",
    "            if grid[r][c] == pivot_color:\n",
    "                pivot_c = c\n",
    "                break\n",
    "        if pivot_c != -1:\n",
    "            break\n",
    "\n",
    "    if pivot_c != -1:\n",
    "        for r in range(R):\n",
    "            for offset in range(1, C):\n",
    "                left_c = pivot_c - offset\n",
    "                right_c = pivot_c + offset\n",
    "                if left_c >= 0 and right_c < C:\n",
    "                    if grid[r][left_c] != 0:\n",
    "                        result[r][right_c] = grid[r][left_c]\n",
    "\n",
    "    return result\n",
    "\n",
    "def slide_color(grid, color, dr, dc):\n",
    "    \"\"\"\n",
    "    Slides specific cells of a given color in target directions.\n",
    "    \"\"\"\n",
    "    result = clone_grid(grid)\n",
    "    R = len(result)\n",
    "    C = len(result[0])\n",
    "    to_move = []\n",
    "\n",
    "    for r in range(R):\n",
    "        for c in range(C):\n",
    "            if result[r][c] == color:\n",
    "                to_move.append({\"r\": r, \"c\": c, \"val\": result[r][c]})\n",
    "                result[r][c] = 0\n",
    "\n",
    "    for item in to_move:\n",
    "        target_r = item[\"r\"] + dr\n",
    "        target_c = item[\"c\"] + dc\n",
    "        if 0 <= target_r < R and 0 <= target_c < C:\n",
    "            result[target_r][target_c] = item[\"val\"]\n",
    "\n",
    "    return result\n",
    "\n",
    "def mirror_grid(grid, axis):\n",
    "    \"\"\"\n",
    "    Reflects the grid around its central axes.\n",
    "    \"\"\"\n",
    "    if axis == \"vertical\":\n",
    "        return [row[::-1] for row in grid]\n",
    "    elif axis == \"horizontal\":\n",
    "        return grid[::-1]\n",
    "    return clone_grid(grid)\n",
    "\n",
    "def rotate_grid(grid, degrees):\n",
    "    \"\"\"\n",
    "    Rotates the grid clockwise.\n",
    "    \"\"\"\n",
    "    if degrees == 180:\n",
    "        return [row[::-1] for row in grid[::-1]]\n",
    "    elif degrees == 90:\n",
    "        return [list(x) for x in zip(*grid[::-1])]\n",
    "    elif degrees == 270:\n",
    "        return [list(x) for x in zip(*grid)][::-1]\n",
    "    return clone_grid(grid)\n",
    "\n",
    "def flood_fill(grid, start_r, start_c, fill_color, boundary_color):\n",
    "    \"\"\"\n",
    "    Fills enclosed structures without crossing boundaries.\n",
    "    \"\"\"\n",
    "    result = clone_grid(grid)\n",
    "    R = len(result)\n",
    "    C = len(result[0])\n",
    "    visited = [[False] * C for _ in range(R)]\n",
    "    queue = [(start_r, start_c)]\n",
    "    \n",
    "    while queue:\n",
    "        r, c = queue.pop(0)\n",
    "        if r < 0 or r >= R or c < 0 or c >= C:\n",
    "            continue\n",
    "        if visited[r][c]:\n",
    "            continue\n",
    "        if result[r][c] == boundary_color or result[r][c] == fill_color:\n",
    "            continue\n",
    "        \n",
    "        visited[r][c] = True\n",
    "        result[r][c] = fill_color\n",
    "        \n",
    "        queue.append((r + 1, c))\n",
    "        queue.append((r - 1, c))\n",
    "        queue.append((r, c + 1))\n",
    "        queue.append((r, c - 1))\n",
    "        \n",
    "    return result\n",
    "\n",
    "def replace_color(grid, target_color, replacement_color):\n",
    "    \"\"\"\n",
    "    Replaces colors globally.\n",
    "    \"\"\"\n",
    "    return [[replacement_color if cell == target_color else cell for cell in row] for row in grid]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4f7dbcec",
   "metadata": {
    "papermill": {
     "duration": 0.002341,
     "end_time": "2026-07-31T01:32:30.874920+00:00",
     "exception": false,
     "start_time": "2026-07-31T01:32:30.872579+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "class DrTEmpatheticGenerator:\n",
    "    \"\"\"\n",
    "    Offline Empathetic Response Generator simulating Dr. T's compassionate\n",
    "    bedside manner and verified medical grounding.\n",
    "    \"\"\"\n",
    "    def generate_response(self, text, analysis, phase):\n",
    "        emotions_str = \", \".join(analysis['emotions'])\n",
    "        symptoms_str = \", \".join(analysis['symptoms'])\n",
    "\n",
    "        response = (\n",
    "            f\"Dear heart, I hear you so deeply. Pouring your feelings out about {symptoms_str.lower()} \"\n",
    "            f\"takes immense bravery. It is completely natural to experience {emotions_str.lower()} \"\n",
    "            f\"during the {phase} stage.\\n\\n\"\n",
    "            f\"Please remember that your feelings are valid and your body is fighting hard for you every second. \"\n",
    "            f\"Here are 3 supportive clinical care steps you can take right now:\\n\"\n",
    "            f\"1. Rest and hydrate with warm fluids or electrolyte-rich solutions.\\n\"\n",
    "            f\"2. Practice gentle 4-7-8 diaphragmatic breathing to calm your nervous system.\\n\"\n",
    "            f\"3. Note down these exact symptoms so we can review them together with your care team.\\n\\n\"\n",
    "            f\"I am standing right beside you through this journey. You are never alone.\"\n",
    "        )\n",
    "        return response\n",
    "\n",
    "generator = DrTEmpatheticGenerator()\n",
    "print(\"[+] Dr. T Empathetic Generator active.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "59696f3e",
   "metadata": {
    "papermill": {
     "duration": 0.00218,
     "end_time": "2026-07-31T01:32:30.879424+00:00",
     "exception": false,
     "start_time": "2026-07-31T01:32:30.877244+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "db319855",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-07-31T01:32:30.886118Z",
     "iopub.status.busy": "2026-07-31T01:32:30.885276Z",
     "iopub.status.idle": "2026-07-31T01:32:30.891608Z",
     "shell.execute_reply": "2026-07-31T01:32:30.890751Z"
    },
    "papermill": {
     "duration": 0.011739,
     "end_time": "2026-07-31T01:32:30.893410+00:00",
     "exception": false,
     "start_time": "2026-07-31T01:32:30.881671+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[+] Dr. T Empathetic Generator active.\n"
     ]
    }
   ],
   "source": [
    "class DrTEmpatheticGenerator:\n",
    "    \"\"\"\n",
    "    Offline Empathetic Response Generator simulating Dr. T's compassionate\n",
    "    bedside manner and verified medical grounding.\n",
    "    \"\"\"\n",
    "    def generate_response(self, text, analysis, phase):\n",
    "        emotions_str = \", \".join(analysis['emotions'])\n",
    "        symptoms_str = \", \".join(analysis['symptoms'])\n",
    "\n",
    "        response = (\n",
    "            f\"Dear heart, I hear you so deeply. Pouring your feelings out about {symptoms_str.lower()} \"\n",
    "            f\"takes immense bravery. It is completely natural to experience {emotions_str.lower()} \"\n",
    "            f\"during the {phase} stage.\\n\\n\"\n",
    "            f\"Please remember that your feelings are valid and your body is fighting hard for you every second. \"\n",
    "            f\"Here are 3 supportive clinical care steps you can take right now:\\n\"\n",
    "            f\"1. Rest and hydrate with warm fluids or electrolyte-rich solutions.\\n\"\n",
    "            f\"2. Practice gentle 4-7-8 diaphragmatic breathing to calm your nervous system.\\n\"\n",
    "            f\"3. Note down these exact symptoms so we can review them together with your care team.\\n\\n\"\n",
    "            f\"I am standing right beside you through this journey. You are never alone.\"\n",
    "        )\n",
    "        return response\n",
    "\n",
    "generator = DrTEmpatheticGenerator()\n",
    "print(\"[+] Dr. T Empathetic Generator active.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c116d9da",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-07-31T01:32:30.900888Z",
     "iopub.status.busy": "2026-07-31T01:32:30.899945Z",
     "iopub.status.idle": "2026-07-31T01:32:30.943190Z",
     "shell.execute_reply": "2026-07-31T01:32:30.942082Z"
    },
    "papermill": {
     "duration": 0.049308,
     "end_time": "2026-07-31T01:32:30.945158+00:00",
     "exception": false,
     "start_time": "2026-07-31T01:32:30.895850+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Processing Patient Narratives Offline...\n",
      "\n",
      "===========================================================================\n",
      "PROCESSED R&D CLINICAL CASES (DATAFRAME PREVIEW):\n",
      "===========================================================================\n",
      "     caseId     patientAlias              treatmentPhase                                                                                                                                                                                                             rndResearchInsights\n",
      "RND-KAG-101 PATIENT_ANON_101 Mid-Treatment / Active Care       R&D Medical Device Rec: Implement vein-visualization IR scanner & micro-needle infusion ports to lower phlebotomy trauma. | R&D Pharma Rec: Formulate fast-acting sublingual anti-emetic strips prior to infusion cycles.\n",
      "RND-KAG-102 PATIENT_ANON_102   Post-Treatment / Recovery R&D Pharma Rec: Formulate fast-acting sublingual anti-emetic strips prior to infusion cycles. | R&D Diagnostics Rec: Pagophagia is a strong biomarker for severe iron deficiency anemia; trigger automated ferritin lab panels.\n",
      "RND-KAG-103 PATIENT_ANON_103   Post-Treatment / Recovery                                                                                                                R&D Care Quality Rec: Enhance patient-centered empathetic check-ins and provide personalized recovery schedules.\n",
      "\n",
      "[✓] Successfully exported 3 cases to 'drt_rnd_cases_kaggle_export.csv' and 'drt_rnd_cases_kaggle_export.json'!\n"
     ]
    }
   ],
   "source": [
    "sample_patient_narratives = [\n",
    "    \"I'm so scared of my upcoming chemotherapy infusion tomorrow. The needles always hurt and my veins collapse. I can't stop crying. Contact me at patient@example.com or Dr. Smith.\",\n",
    "    \"Day 5 after my procedure and the nausea is unbearable. I've been craving ice constantly and crunching on ice cubes all day.\",\n",
    "    \"Finished my 6th cycle last week! I feel so fatigued and brain foggy, but I'm trying to remain hopeful for my recovery scan.\"\n",
    "]\n",
    "\n",
    "processed_records = []\n",
    "\n",
    "print(\"\\nProcessing Patient Narratives Offline...\")\n",
    "for idx, raw_story in enumerate(sample_patient_narratives, start=101):\n",
    "    clean_text, alias = anonymizer.anonymize(raw_story, patient_id_seq=idx)\n",
    "    nlp_res = extractor.analyze(clean_text)\n",
    "    response_text = generator.generate_response(clean_text, nlp_res, nlp_res['phase'])\n",
    "\n",
    "    record = {\n",
    "        'caseId': f\"RND-KAG-{idx}\",\n",
    "        'patientAlias': alias,\n",
    "        'treatmentPhase': nlp_res['phase'],\n",
    "        'patientStory': clean_text,\n",
    "        'emotionsDetected': nlp_res['emotions'],\n",
    "        'symptomsDetected': nlp_res['symptoms'],\n",
    "        'rndResearchInsights': nlp_res['rnd_recommendations'],\n",
    "        'drTResponse': response_text,\n",
    "        'anonymizedSummary': f\"Offline Kaggle case analyzing {', '.join(nlp_res['emotions'])} and {', '.join(nlp_res['symptoms'])}.\",\n",
    "        'createdAt': datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M\")\n",
    "    }\n",
    "    processed_records.append(record)\n",
    "\n",
    "# Convert to Pandas DataFrame\n",
    "df = pd.DataFrame(processed_records)\n",
    "print(\"\\n\" + \"=\" * 75)\n",
    "print(\"PROCESSED R&D CLINICAL CASES (DATAFRAME PREVIEW):\")\n",
    "print(\"=\" * 75)\n",
    "print(df[['caseId', 'patientAlias', 'treatmentPhase', 'rndResearchInsights']].to_string(index=False))\n",
    "\n",
    "# Export to CSV & JSON\n",
    "csv_path = \"drt_rnd_cases_kaggle_export.csv\"\n",
    "json_path = \"drt_rnd_cases_kaggle_export.json\"\n",
    "\n",
    "df.to_csv(csv_path, index=False)\n",
    "with open(json_path, 'w', encoding='utf-8') as f:\n",
    "    json.dump(processed_records, f, indent=2)\n",
    "\n",
    "print(f\"\\n[✓] Successfully exported {len(processed_records)} cases to '{csv_path}' and '{json_path}'!\")"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [],
   "dockerImageVersionId": 28755,
   "isGpuEnabled": false,
   "isInternetEnabled": false,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 8.134987,
   "end_time": "2026-07-31T01:32:31.867892+00:00",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-07-31T01:32:23.732905+00:00",
   "version": "2.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
