import React, { useState } from 'react';
import { 
  Database, GitBranch, ShieldCheck, Sparkles, Server, Terminal, 
  Code2, Cpu, FileCode2, Play, CheckCircle2, AlertTriangle, RefreshCw, 
  Layers, ArrowRight, GitPullRequest, Search, FileText, Check, Tag, Activity, Globe,
  Radio, ShieldAlert, CpuIcon, CheckSquare, Zap, Lock, BookOpen
} from 'lucide-react';

export type ChallengeTab = 'agents_work' | 'code_gen' | 'ml_agents' | 'data_contracts' | 'wildcard_drt';

interface MetadataEntity {
  urn: string;
  name: string;
  type: 'dataset' | 'feature_store' | 'ml_model' | 'pipeline' | 'dashboard';
  platform: 'snowflake' | 'postgres' | 'kafka' | 'airflow' | 'medgemma' | 'dbt';
  owners: string[];
  tags: string[];
  fieldsCount: number;
  qualityScore: number;
  upstreamCount: number;
  downstreamCount: number;
  schema: Array<{ name: string; type: string; description: string; nullable: boolean; isPII?: boolean }>;
}

export const DataHubAgentSuite: React.FC = () => {
  const [activeChallenge, setActiveChallenge] = useState<ChallengeTab>('agents_work');
  const [selectedEntityUrn, setSelectedEntityUrn] = useState<string>('urn:li:dataset:(urn:li:dataPlatform:postgres,drt_clinical_v2,PROD)');
  const [isAgentRunning, setIsAgentRunning] = useState<boolean>(false);
  const [webhookActive, setWebhookActive] = useState<boolean>(true);
  
  const [agentLog, setAgentLog] = useState<Array<{ timestamp: string; agent: string; message: string; type: 'info' | 'success' | 'warning' | 'error' }>>([
    { timestamp: new Date().toLocaleTimeString(), agent: 'DataHub MCP Agent', message: 'Connected to DataHub GMS endpoint & Live Kafka Webhook Stream (gms-webhooks-prod)', type: 'info' },
    { timestamp: new Date().toLocaleTimeString(), agent: 'Context Kit Reader', message: 'Fetched 14 dataset entities, 3 ML model endpoints, 5 Airflow DAGs from DataHub Context Kit', type: 'info' },
    { timestamp: new Date().toLocaleTimeString(), agent: 'Lineage Inspector', message: 'Constructed end-to-end lineage graph: postgres.drt_clinical_v2 -> dbt.longevity_biomarkers -> feature_store.patient_biomarkers -> medgemma-27b-v1', type: 'success' },
    { timestamp: new Date().toLocaleTimeString(), agent: 'MedGemma Telemetry Guard', message: 'Multi-hospital clinical trial metrics synced: Mayo Clinic (99.2%), Johns Hopkins (98.9%), Charité Berlin (99.1%)', type: 'info' }
  ]);

  // Challenge 2: Generated Code State
  const [codeArtifactType, setCodeArtifactType] = useState<'dbt' | 'airflow' | 'pyspark'>('dbt');
  const [generatedCode, setGeneratedCode] = useState<string>(`-- dbt Model generated by DataHub Metadata-Aware Agent
-- Source Entity: urn:li:dataset:(urn:li:dataPlatform:postgres,drt_clinical_v2,PROD)
-- Auto-enforces FHIR & DataHub Contract Constraints

with raw_clinical as (
    select
        patient_id,
        recorded_at,
        systolic_bp::integer as systolic_bp,
        diastolic_bp::integer as diastolic_bp,
        hba1c_level::numeric(4,2) as hba1c_level,
        crp_biomarker_mg_l::numeric(5,2) as crp_biomarker,
        longevity_score::integer as longevity_score,
        datahub_quality_status
    from {{ source('drt_platform', 'drt_clinical_v2') }}
    where is_anonymized = true
),

biomarker_features as (
    select
        patient_id,
        date_trunc('day', recorded_at) as observation_date,
        avg(systolic_bp) as avg_systolic_bp,
        avg(diastolic_bp) as avg_diastolic_bp,
        avg(hba1c_level) as avg_hba1c,
        avg(crp_biomarker) as avg_crp,
        max(longevity_score) as max_longevity_score,
        count(*) as total_observations
    from raw_clinical
    group by 1, 2
)

select * from biomarker_features;`);

  const [prCreated, setPrCreated] = useState<boolean>(false);

  // Challenge 3: ML Lineage Drift simulation & MedGemma Telemetry state
  const [mlDriftSimulated, setMlDriftSimulated] = useState<boolean>(false);
  const [mlAlertResolved, setMlAlertResolved] = useState<boolean>(false);
  const [epistemicUncertainty, setEpistemicUncertainty] = useState<number>(0.042);
  const [demographicBias, setDemographicBias] = useState<number>(0.018);

  // Data Contract State
  const [contractVerified, setContractVerified] = useState<boolean>(true);
  const [contractSpec, setContractSpec] = useState<string>(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "DrTClinicalV2DataContract",
  "description": "Generated directly from DataHub Glossary Terms: PHI_Data, VitalSigns, BiologicalAge",
  "type": "object",
  "properties": {
    "patient_id": {
      "type": "string",
      "format": "uuid",
      "datahub_glossary_term": "PHI_Data",
      "pii_masked": true
    },
    "systolic_bp": {
      "type": "integer",
      "minimum": 60,
      "maximum": 240,
      "datahub_glossary_term": "VitalSigns"
    },
    "hba1c_level": {
      "type": "number",
      "minimum": 3.0,
      "maximum": 18.0,
      "datahub_glossary_term": "Biomarker"
    }
  },
  "required": ["patient_id", "recorded_at", "longevity_score"],
  "great_expectations_assertions": [
    "expect_column_values_to_not_be_null(column='patient_id')",
    "expect_column_min_to_be_between(column='systolic_bp', min_value=60, max_value=240)",
    "expect_column_pair_values_A_to_be_greater_than_B(column_A='systolic_bp', column_B='diastolic_bp')"
  ]
}`);

  // Mock Entities from DataHub Metadata Catalog
  const metadataEntities: MetadataEntity[] = [
    {
      urn: 'urn:li:dataset:(urn:li:dataPlatform:postgres,drt_clinical_v2,PROD)',
      name: 'postgres.drt_clinical_v2',
      type: 'dataset',
      platform: 'postgres',
      owners: ['Dr. T Chancellor', 'Data Engineering Swarm'],
      tags: ['FHIR-Compliant', 'PII-Protected', 'Tier-1-Core'],
      fieldsCount: 12,
      qualityScore: 98.4,
      upstreamCount: 2,
      downstreamCount: 4,
      schema: [
        { name: 'patient_id', type: 'VARCHAR(64)', description: 'Anonymized FHIR patient UUID', nullable: false, isPII: true },
        { name: 'recorded_at', type: 'TIMESTAMP', description: 'Clinical measurement timestamp', nullable: false },
        { name: 'systolic_bp', type: 'INTEGER', description: 'Systolic blood pressure (mmHg)', nullable: true },
        { name: 'diastolic_bp', type: 'INTEGER', description: 'Diastolic blood pressure (mmHg)', nullable: true },
        { name: 'hba1c_level', type: 'NUMERIC(4,2)', description: 'Glycated hemoglobin percentage', nullable: true },
        { name: 'crp_biomarker_mg_l', type: 'NUMERIC(5,2)', description: 'C-Reactive Protein biomarker', nullable: true },
        { name: 'longevity_score', type: 'INTEGER', description: 'Dr. T Longevity Index (0-100)', nullable: false }
      ]
    },
    {
      urn: 'urn:li:feature_store:(urn:li:dataPlatform:snowflake,patient_biomarker_features,PROD)',
      name: 'snowflake.patient_biomarker_features',
      type: 'feature_store',
      platform: 'snowflake',
      owners: ['MLOps Team', 'Clinical AI Swarm'],
      tags: ['ML-Feature-Store', 'Real-Time-Inference'],
      fieldsCount: 18,
      qualityScore: 99.1,
      upstreamCount: 1,
      downstreamCount: 2,
      schema: [
        { name: 'feature_patient_uuid', type: 'STRING', description: 'Feature key patient identifier', nullable: false },
        { name: 'mean_crp_7d', type: 'FLOAT', description: '7-day rolling mean C-Reactive Protein', nullable: false },
        { name: 'hba1c_trend_delta', type: 'FLOAT', description: 'Quarterly HbA1c trajectory delta', nullable: false },
        { name: 'longevity_score_normalized', type: 'FLOAT', description: 'Normalized score [0.0 - 1.0]', nullable: false }
      ]
    },
    {
      urn: 'urn:li:mlModel:(urn:li:dataPlatform:medgemma,medgemma_27b_v1,PROD)',
      name: 'medgemma-27b-longevity-diagnostic',
      type: 'ml_model',
      platform: 'medgemma',
      owners: ['Clinical AI Research Hub'],
      tags: ['Production-ML', 'MedGemma-27B', 'High-Risk'],
      fieldsCount: 8,
      qualityScore: 96.5,
      upstreamCount: 1,
      downstreamCount: 3,
      schema: [
        { name: 'input_feature_vector', type: 'TENSOR[FLOAT, 128]', description: 'Biomarker feature embedding', nullable: false },
        { name: 'predicted_risk_level', type: 'STRING', description: 'Cardio-longevity risk stratification', nullable: false },
        { name: 'confidence_score', type: 'FLOAT', description: 'Model epistemic confidence', nullable: false }
      ]
    }
  ];

  const currentEntity = metadataEntities.find(e => e.urn === selectedEntityUrn) || metadataEntities[0];

  const triggerLiveGmsWebhook = () => {
    const timeStr = new Date().toLocaleTimeString();
    setAgentLog(prev => [
      ...prev,
      { timestamp: timeStr, agent: 'Live GMS Webhook', message: '⚡ Kafka Event Received: MetadataChangeEvent (MCE) for urn:li:dataset:drt_clinical_v2 [aspect: schemaMetadata]', type: 'warning' },
      { timestamp: timeStr, agent: 'DataHub Sentinel Agent', message: '🔔 Triggered instant automated remediation workflow for mutated schema aspect.', type: 'info' },
      { timestamp: timeStr, agent: 'Data Contract Guard', message: '✅ Validated live mutation against JSON Schema contract: 0 field conflicts detected.', type: 'success' }
    ]);
  };

  const handleRunAgentAction = (actionName: string) => {
    setIsAgentRunning(true);
    setAgentLog(prev => [
      ...prev,
      { timestamp: new Date().toLocaleTimeString(), agent: 'DataHub MCP Agent', message: `Executing automated workflow: ${actionName}...`, type: 'info' }
    ]);

    setTimeout(() => {
      if (activeChallenge === 'agents_work') {
        setAgentLog(prev => [
          ...prev,
          { timestamp: new Date().toLocaleTimeString(), agent: 'Schema Compliance Agent', message: 'Read schema from DataHub Context Kit. Verified 12 columns, 0 missing assertions.', type: 'info' },
          { timestamp: new Date().toLocaleTimeString(), agent: 'Metadata Writer Agent', message: 'Wrote back updated tags [DataHub-Verified, Governance-Approved] to URN urn:li:dataset:drt_clinical_v2 via DataHub MCP API', type: 'success' }
        ]);
      } else if (activeChallenge === 'code_gen') {
        setAgentLog(prev => [
          ...prev,
          { timestamp: new Date().toLocaleTimeString(), agent: 'dbt CodeGen Agent', message: 'Inspected DataHub schema & upstream contracts. Generated dbt transform model with zero field discrepancies.', type: 'info' },
          { timestamp: new Date().toLocaleTimeString(), agent: 'Git PR Agent', message: 'Created GitHub Pull Request #142 in repo drt-institute/clinical-pipelines with generated dbt artifact.', type: 'success' }
        ]);
        setPrCreated(true);
      } else if (activeChallenge === 'ml_agents') {
        setAgentLog(prev => [
          ...prev,
          { timestamp: new Date().toLocaleTimeString(), agent: 'ML Lineage Guard', message: 'Traced downstream path: postgres.drt_clinical_v2 -> feature_store -> medgemma-27b-v1.', type: 'info' },
          { timestamp: new Date().toLocaleTimeString(), agent: 'MedGemma Telemetry Agent', message: 'Calibrated epistemic uncertainty (0.042) & demographic parity bias score (0.018) across 3 trial hospitals.', type: 'success' },
          { timestamp: new Date().toLocaleTimeString(), agent: 'Drift Auto-Patcher', message: 'Applied schema assertion patch & written updated feature store schema back to DataHub catalog.', type: 'success' }
        ]);
        setMlAlertResolved(true);
      } else if (activeChallenge === 'data_contracts') {
        setAgentLog(prev => [
          ...prev,
          { timestamp: new Date().toLocaleTimeString(), agent: 'Contract Enforcer Agent', message: 'Generated JSON Schema & Great Expectations contract directly from DataHub Glossary terms.', type: 'info' },
          { timestamp: new Date().toLocaleTimeString(), agent: 'DataHub Aspect Writer', message: 'Emitted dataContract aspect to DataHub GMS REST endpoint for URN urn:li:dataset:drt_clinical_v2.', type: 'success' }
        ]);
        setContractVerified(true);
      } else {
        setAgentLog(prev => [
          ...prev,
          { timestamp: new Date().toLocaleTimeString(), agent: 'Cosmos Bio Governance Agent', message: 'Linked Interstellar Bio-Crop Harvest (Cosmos Green Agent) to DataHub Clinical Ledger.', type: 'info' },
          { timestamp: new Date().toLocaleTimeString(), agent: 'FHIR Compliance Validator', message: 'Validated 100% FHIR R4 resource compatibility across Dr. T Longevity Datasets.', type: 'success' }
        ]);
      }
      setIsAgentRunning(false);
    }, 1200);
  };

  const handleSimulateDrift = () => {
    setMlDriftSimulated(true);
    setMlAlertResolved(false);
    setEpistemicUncertainty(0.184); // Elevated uncertainty
    setDemographicBias(0.082); // Elevated bias risk
    setAgentLog(prev => [
      ...prev,
      { timestamp: new Date().toLocaleTimeString(), agent: 'DataHub Lineage Sensor', message: '⚠️ WARNING: Detected upstream schema type mismatch in "crp_biomarker_mg_l" (expected NUMERIC, got STRING in staging).', type: 'warning' },
      { timestamp: new Date().toLocaleTimeString(), agent: 'MedGemma Telemetry Monitor', message: '🚨 ALERT: Epistemic uncertainty spiked to 0.184! Demographic bias threshold exceeded (0.082).', type: 'error' },
      { timestamp: new Date().toLocaleTimeString(), agent: 'Production ML Lineage Protector', message: '🛑 ALERT: Downstream ML Model "medgemma-27b-longevity-diagnostic" is at risk of silent failure!', type: 'error' }
    ]);
  };

  const generateCodeForType = (type: 'dbt' | 'airflow' | 'pyspark') => {
    setCodeArtifactType(type);
    if (type === 'dbt') {
      setGeneratedCode(`-- dbt Model generated by DataHub Metadata-Aware Agent
-- Source Entity: urn:li:dataset:(urn:li:dataPlatform:postgres,drt_clinical_v2,PROD)

with raw_clinical as (
    select
        patient_id,
        recorded_at,
        systolic_bp::integer as systolic_bp,
        diastolic_bp::integer as diastolic_bp,
        hba1c_level::numeric(4,2) as hba1c_level,
        crp_biomarker_mg_l::numeric(5,2) as crp_biomarker,
        longevity_score::integer as longevity_score
    from {{ source('drt_platform', 'drt_clinical_v2') }}
)
select * from raw_clinical;`);
    } else if (type === 'airflow') {
      setGeneratedCode(`# Airflow DAG generated via DataHub Metadata API
from airflow import DAG
from airflow.providers.dbt.cloud.operators.dbt import DbtCloudRunJobOperator
from datetime import datetime, timedelta

default_args = {
    'owner': 'dr_t_datahub_agent',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}

with DAG(
    'datahub_metadata_aware_clinical_etl',
    default_args=default_args,
    schedule_interval='@hourly',
    catchup=False,
    tags=['datahub', 'clinical_ai', 'dr_t']
) as dag:

    run_dbt_clinical = DbtCloudRunJobOperator(
        task_id='dbt_run_clinical_v2',
        job_id=48210,
        check_interval=10,
        timeout=300,
    )`);
    } else {
      setGeneratedCode(`# PySpark Ingestion Pipeline generated from DataHub Context Kit
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, avg, window

spark = SparkSession.builder \\
    .appName("DataHub_MetadataAware_Ingest") \\
    .config("spark.sql.execution.arrow.pyspark.enabled", "true") \\
    .getOrCreate()

# Read schema metadata dynamically from DataHub MCP
df = spark.read.format("postgres") \\
    .option("url", "jdbc:postgresql://drt-db.internal:5432/longevity") \\
    .option("dbtable", "drt_clinical_v2") \\
    .load()

# Transform & Compute Rolling Biomarkers
processed_df = df.filter(col("is_anonymized") == True) \\
    .withColumn("hba1c_level", col("hba1c_level").cast("double"))

processed_df.write.format("delta").mode("overwrite").saveAsTable("snowflake.patient_biomarker_features")`);
    }
  };

  return (
    <div className="w-full max-w-7xl mx-auto p-4 sm:p-6 space-y-6">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-stone-900 via-amber-950 to-stone-900 border border-amber-500/30 rounded-3xl p-6 sm:p-8 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-amber-500/10 rounded-full filter blur-3xl pointer-events-none"></div>
        <div className="relative z-10 flex flex-col md:flex-row md:items-center md:justify-between gap-6">
          <div className="space-y-3">
            <div className="flex items-center gap-3">
              <div className="p-3 bg-gradient-to-br from-amber-500 to-rose-600 rounded-2xl shadow-lg">
                <Database className="w-7 h-7 text-white" />
              </div>
              <div>
                <span className="text-xs font-mono text-amber-400 font-bold uppercase tracking-widest flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
                  DataHub Control Plane • Dr. T Platform
                </span>
                <h1 className="text-2xl sm:text-4xl font-black text-white tracking-tight font-display">
                  DataHub AI Agent Governance
                </h1>
              </div>
            </div>
            <p className="text-stone-300 text-sm max-w-3xl leading-relaxed">
              Powered by DataHub open-source metadata infrastructure (MCP Server & Agent Context Kit). 
              Build metadata-aware AI agents that inspect end-to-end schemas, enforce automated data contracts, stream live GMS webhooks, and protect MedGemma multi-hospital clinical models.
            </p>
          </div>

          {/* Live GMS Webhooks & MCP Server Badge */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 bg-stone-950/80 backdrop-blur border border-amber-500/30 p-4 rounded-2xl">
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <Server className="w-4 h-4 text-emerald-400" />
                <span className="text-xs font-bold text-white font-mono">DataHub MCP Server</span>
              </div>
              <div className="flex items-center gap-2 text-[11px] text-stone-400 font-mono">
                <Radio className="w-3.5 h-3.5 text-amber-400 animate-pulse" />
                <span>Kafka Webhooks: ACTIVE</span>
              </div>
            </div>
            <button
              onClick={triggerLiveGmsWebhook}
              className="px-3 py-1.5 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 text-xs font-mono font-bold border border-amber-500/40 flex items-center gap-2 cursor-pointer transition-all"
            >
              <Zap className="w-3.5 h-3.5 text-amber-400" />
              Trigger GMS Webhook Event
            </button>
          </div>
        </div>

        {/* Challenge Selection Navigation */}
        <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mt-8 pt-6 border-t border-stone-800">
          <button
            onClick={() => setActiveChallenge('agents_work')}
            className={`p-3.5 rounded-2xl text-left transition-all border cursor-pointer flex flex-col justify-between ${
              activeChallenge === 'agents_work'
                ? 'bg-amber-500/20 border-amber-500 text-white shadow-lg'
                : 'bg-stone-900/60 border-stone-800 text-stone-400 hover:text-stone-200 hover:bg-stone-800/60'
            }`}
          >
            <div className="flex items-center gap-2 font-bold text-xs uppercase tracking-wider mb-1">
              <Cpu className="w-4 h-4 text-amber-400" />
              Autonomous Data Squad
            </div>
            <div className="font-bold text-sm text-white">DataHub Agent Squad</div>
            <div className="text-[11px] text-stone-400 mt-1 line-clamp-1">MCP Multi-Agent Data Squad & Writeback</div>
          </button>

          <button
            onClick={() => setActiveChallenge('code_gen')}
            className={`p-3.5 rounded-2xl text-left transition-all border cursor-pointer flex flex-col justify-between ${
              activeChallenge === 'code_gen'
                ? 'bg-amber-500/20 border-amber-500 text-white shadow-lg'
                : 'bg-stone-900/60 border-stone-800 text-stone-400 hover:text-stone-200 hover:bg-stone-800/60'
            }`}
          >
            <div className="flex items-center gap-2 font-bold text-xs uppercase tracking-wider mb-1">
              <Code2 className="w-4 h-4 text-rose-400" />
              Pipeline CodeGen
            </div>
            <div className="font-bold text-sm text-white">Metadata Engineering</div>
            <div className="text-[11px] text-stone-400 mt-1 line-clamp-1">dbt, Airflow & Git PR Artifacts</div>
          </button>

          <button
            onClick={() => setActiveChallenge('ml_agents')}
            className={`p-3.5 rounded-2xl text-left transition-all border cursor-pointer flex flex-col justify-between ${
              activeChallenge === 'ml_agents'
                ? 'bg-amber-500/20 border-amber-500 text-white shadow-lg'
                : 'bg-stone-900/60 border-stone-800 text-stone-400 hover:text-stone-200 hover:bg-stone-800/60'
            }`}
          >
            <div className="flex items-center gap-2 font-bold text-xs uppercase tracking-wider mb-1">
              <ShieldCheck className="w-4 h-4 text-emerald-400" />
              ML Lineage Guard
            </div>
            <div className="font-bold text-sm text-white">MedGemma Telemetry</div>
            <div className="text-[11px] text-stone-400 mt-1 line-clamp-1">Bias & Epistemic Uncertainty Shield</div>
          </button>

          <button
            onClick={() => setActiveChallenge('data_contracts')}
            className={`p-3.5 rounded-2xl text-left transition-all border cursor-pointer flex flex-col justify-between ${
              activeChallenge === 'data_contracts'
                ? 'bg-amber-500/20 border-amber-500 text-white shadow-lg'
                : 'bg-stone-900/60 border-stone-800 text-stone-400 hover:text-stone-200 hover:bg-stone-800/60'
            }`}
          >
            <div className="flex items-center gap-2 font-bold text-xs uppercase tracking-wider mb-1">
              <CheckSquare className="w-4 h-4 text-cyan-400" />
              Data Contracts
            </div>
            <div className="font-bold text-sm text-white">Glossary Contract Guard</div>
            <div className="text-[11px] text-stone-400 mt-1 line-clamp-1">JSON Schema & Great Expectations</div>
          </button>

          <button
            onClick={() => setActiveChallenge('wildcard_drt')}
            className={`p-3.5 rounded-2xl text-left transition-all border cursor-pointer flex flex-col justify-between ${
              activeChallenge === 'wildcard_drt'
                ? 'bg-amber-500/20 border-amber-500 text-white shadow-lg'
                : 'bg-stone-900/60 border-stone-800 text-stone-400 hover:text-stone-200 hover:bg-stone-800/60'
            }`}
          >
            <div className="flex items-center gap-2 font-bold text-xs uppercase tracking-wider mb-1">
              <Sparkles className="w-4 h-4 text-amber-300" />
              Ecosystem Hub
            </div>
            <div className="font-bold text-sm text-white">Bio-Market Governance</div>
            <div className="text-[11px] text-stone-400 mt-1 line-clamp-1">Dr. T Bio-Market DataHub Governance</div>
          </button>
        </div>
      </div>

      {/* Main Grid: DataHub Live Metadata Context + Active Challenge Workspace */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Column (5 Cols): DataHub Context Kit Explorer & Lineage View */}
        <div className="lg:col-span-5 space-y-6">
          <div className="bg-stone-900/90 border border-stone-800 rounded-3xl p-5 shadow-xl space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-base font-bold text-white flex items-center gap-2 font-display">
                <Layers className="w-5 h-5 text-amber-400" />
                DataHub Catalog Entities
              </h2>
              <span className="text-[11px] font-mono text-stone-400 bg-stone-800 px-2.5 py-1 rounded-lg">
                Context Kit SDK
              </span>
            </div>

            {/* Entity List */}
            <div className="space-y-2">
              {metadataEntities.map(entity => (
                <div
                  key={entity.urn}
                  onClick={() => setSelectedEntityUrn(entity.urn)}
                  className={`p-3.5 rounded-2xl border transition-all cursor-pointer ${
                    selectedEntityUrn === entity.urn
                      ? 'bg-stone-800 border-amber-500/70 text-white shadow-md'
                      : 'bg-stone-950/60 border-stone-800/80 text-stone-400 hover:border-stone-700 hover:text-stone-200'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="font-mono text-xs font-bold text-amber-300 truncate">
                      {entity.name}
                    </div>
                    <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-stone-900 text-amber-400 border border-amber-500/30">
                      {entity.type}
                    </span>
                  </div>
                  <div className="flex items-center gap-3 text-xs text-stone-400 mt-2 font-mono">
                    <span>Quality: <strong className="text-emerald-400">{entity.qualityScore}%</strong></span>
                    <span>Fields: <strong>{entity.fieldsCount}</strong></span>
                    <span>Platform: <strong className="uppercase">{entity.platform}</strong></span>
                  </div>
                </div>
              ))}
            </div>

            {/* Selected Entity Details & Schema */}
            <div className="bg-stone-950/80 border border-stone-800 rounded-2xl p-4 space-y-3">
              <div className="flex items-center justify-between border-b border-stone-800 pb-2">
                <span className="text-xs font-mono font-bold text-stone-300">DataHub Field Schema</span>
                <span className="text-[10px] font-mono text-amber-400">{currentEntity.schema.length} Fields Inspected</span>
              </div>
              <div className="max-h-52 overflow-y-auto space-y-2 pr-1 font-mono text-xs">
                {currentEntity.schema.map((field, idx) => (
                  <div key={idx} className="p-2 rounded-xl bg-stone-900 border border-stone-800 flex items-center justify-between">
                    <div>
                      <div className="text-stone-200 font-bold flex items-center gap-1.5">
                        {field.name}
                        {field.isPII && (
                          <span className="text-[9px] px-1.5 py-0.2 rounded bg-rose-950 text-rose-300 border border-rose-800">
                            PII
                          </span>
                        )}
                      </div>
                      <div className="text-[10px] text-stone-400">{field.description}</div>
                    </div>
                    <span className="text-[10px] text-amber-400 bg-stone-950 px-2 py-1 rounded">
                      {field.type}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* End-to-End Lineage Visualizer */}
            <div className="bg-stone-950/90 border border-amber-500/20 rounded-2xl p-4 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-mono font-bold text-amber-300 flex items-center gap-1.5">
                  <GitBranch className="w-4 h-4 text-amber-400" />
                  DataHub End-to-End Lineage
                </span>
                <span className="text-[10px] text-emerald-400 font-mono">Live Sync</span>
              </div>

              <div className="flex flex-col gap-2 font-mono text-xs">
                <div className="p-2.5 rounded-xl bg-stone-900 border border-stone-800 flex items-center justify-between">
                  <span className="text-stone-300 font-bold">1. Source: PostgreSQL</span>
                  <span className="text-[10px] text-stone-400">drt_clinical_v2</span>
                </div>
                <div className="flex justify-center"><ArrowRight className="w-4 h-4 text-amber-400 rotate-90" /></div>
                <div className="p-2.5 rounded-xl bg-stone-900 border border-amber-500/40 flex items-center justify-between">
                  <span className="text-amber-300 font-bold">2. Feature Store</span>
                  <span className="text-[10px] text-stone-400">patient_biomarker_features</span>
                </div>
                <div className="flex justify-center"><ArrowRight className="w-4 h-4 text-amber-400 rotate-90" /></div>
                <div className="p-2.5 rounded-xl bg-stone-900 border border-emerald-500/40 flex items-center justify-between">
                  <span className="text-emerald-300 font-bold">3. Production ML Model</span>
                  <span className="text-[10px] text-stone-400">medgemma-27b-v1</span>
                </div>
              </div>
            </div>

          </div>
        </div>

        {/* Right Column (7 Cols): Challenge Interactive Execution Workspace */}
        <div className="lg:col-span-7 space-y-6">
          <div className="bg-stone-900/90 border border-stone-800 rounded-3xl p-6 shadow-xl space-y-6">
            
            {/* Challenge 1: AGENTS THAT DO REAL WORK */}
            {activeChallenge === 'agents_work' && (
              <div className="space-y-5 animate-fadeIn">
                <div className="border-b border-stone-800 pb-4">
                  <div className="flex items-center gap-2 text-amber-400 text-xs font-mono font-bold uppercase tracking-widest">
                    <Cpu className="w-4 h-4" />
                    Autonomous Data Squad
                  </div>
                  <h3 className="text-xl font-black text-white mt-1 font-display">
                    Agents That Read DataHub & Take Real Action
                  </h3>
                  <p className="text-xs text-stone-400 mt-1">
                    Multi-agent team reads DataHub schemas via MCP Server, executes schema compliance checks, streams live GMS webhooks, and writes back metadata assertions directly to the catalog.
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="bg-stone-950 border border-stone-800 p-4 rounded-2xl space-y-2">
                    <span className="text-xs font-mono font-bold text-amber-300">1. Schema Audit Agent</span>
                    <p className="text-xs text-stone-400">Inspects DataHub URN schemas for non-compliant PII fields and missing descriptions.</p>
                  </div>
                  <div className="bg-stone-950 border border-stone-800 p-4 rounded-2xl space-y-2">
                    <span className="text-xs font-mono font-bold text-rose-300">2. Metadata Writer Agent</span>
                    <p className="text-xs text-stone-400">Writes back verified tags, documentation, and quality scores to DataHub catalog.</p>
                  </div>
                </div>

                <div className="flex flex-col sm:flex-row gap-3">
                  <button
                    onClick={() => handleRunAgentAction('DataHub MCP Squad Inspection & Writeback')}
                    disabled={isAgentRunning}
                    className="flex-1 py-3.5 px-6 rounded-2xl bg-gradient-to-r from-amber-500 to-rose-600 hover:from-amber-600 hover:to-rose-700 text-white font-bold text-sm shadow-xl flex items-center justify-center gap-2 cursor-pointer transition-all disabled:opacity-50"
                  >
                    {isAgentRunning ? (
                      <>
                        <RefreshCw className="w-4 h-4 animate-spin" />
                        DataHub Agent Processing MCP Request...
                      </>
                    ) : (
                      <>
                        <Play className="w-4 h-4 fill-current" />
                        Run DataHub MCP Multi-Agent Squad
                      </>
                    )}
                  </button>

                  <button
                    onClick={triggerLiveGmsWebhook}
                    className="py-3.5 px-4 rounded-2xl bg-stone-950 hover:bg-stone-800 text-amber-400 border border-amber-500/30 text-xs font-mono font-bold flex items-center justify-center gap-2 cursor-pointer transition-all"
                  >
                    <Radio className="w-4 h-4 animate-pulse text-amber-400" />
                    Trigger Live Kafka GMS Webhook Event
                  </button>
                </div>
              </div>
            )}

            {/* Challenge 2: METADATA-AWARE CODEGEN */}
            {activeChallenge === 'code_gen' && (
              <div className="space-y-5 animate-fadeIn">
                <div className="border-b border-stone-800 pb-4">
                  <div className="flex items-center gap-2 text-rose-400 text-xs font-mono font-bold uppercase tracking-widest">
                    <Code2 className="w-4 h-4" />
                    Metadata-Aware Development
                  </div>
                  <h3 className="text-xl font-black text-white mt-1 font-display">
                    Generate Production Pipelines That Work First Try
                  </h3>
                  <p className="text-xs text-stone-400 mt-1">
                    Reads DataHub schema & lineage via Agent Context Kit before generating dbt transform models, Airflow DAGs, and PySpark scripts ready for git merge.
                  </p>
                </div>

                {/* Code Type Selector */}
                <div className="flex items-center gap-2 bg-stone-950 p-1.5 rounded-xl border border-stone-800">
                  <button
                    onClick={() => generateCodeForType('dbt')}
                    className={`flex-1 py-2 px-3 rounded-lg text-xs font-bold font-mono transition-all cursor-pointer ${
                      codeArtifactType === 'dbt' ? 'bg-amber-500 text-white' : 'text-stone-400 hover:text-stone-200'
                    }`}
                  >
                    dbt Model (SQL)
                  </button>
                  <button
                    onClick={() => generateCodeForType('airflow')}
                    className={`flex-1 py-2 px-3 rounded-lg text-xs font-bold font-mono transition-all cursor-pointer ${
                      codeArtifactType === 'airflow' ? 'bg-amber-500 text-white' : 'text-stone-400 hover:text-stone-200'
                    }`}
                  >
                    Airflow DAG (Python)
                  </button>
                  <button
                    onClick={() => generateCodeForType('pyspark')}
                    className={`flex-1 py-2 px-3 rounded-lg text-xs font-bold font-mono transition-all cursor-pointer ${
                      codeArtifactType === 'pyspark' ? 'bg-amber-500 text-white' : 'text-stone-400 hover:text-stone-200'
                    }`}
                  >
                    PySpark Ingest
                  </button>
                </div>

                {/* Code Output Sandbox */}
                <div className="bg-stone-950 border border-stone-800 rounded-2xl p-4 font-mono text-xs relative overflow-hidden">
                  <div className="flex items-center justify-between pb-2 mb-2 border-b border-stone-800 text-stone-400">
                    <span className="flex items-center gap-2">
                      <FileCode2 className="w-4 h-4 text-rose-400" />
                      Generated Artifact ({codeArtifactType.toUpperCase()})
                    </span>
                    <span className="text-[10px] text-emerald-400">DataHub-Verified</span>
                  </div>
                  <pre className="text-amber-200/90 overflow-x-auto max-h-56 leading-relaxed">
                    {generatedCode}
                  </pre>
                </div>

                <div className="flex flex-col sm:flex-row items-center gap-3">
                  <button
                    onClick={() => handleRunAgentAction('Generate Production Code & Create Git PR')}
                    disabled={isAgentRunning}
                    className="flex-1 w-full py-3 px-4 rounded-xl bg-amber-500 hover:bg-amber-600 text-white font-bold text-xs flex items-center justify-center gap-2 cursor-pointer transition-all disabled:opacity-50"
                  >
                    <GitPullRequest className="w-4 h-4" />
                    Create GitHub Pull Request #142
                  </button>
                  {prCreated && (
                    <div className="px-3 py-2 bg-emerald-500/20 text-emerald-300 text-xs font-mono rounded-xl border border-emerald-500/30 flex items-center gap-2">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                      PR #142 Merged into main
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Challenge 3: PRODUCTION ML AGENTS & EXPANDED MEDGEMMA TELEMETRY */}
            {activeChallenge === 'ml_agents' && (
              <div className="space-y-5 animate-fadeIn">
                <div className="border-b border-stone-800 pb-4">
                  <div className="flex items-center gap-2 text-emerald-400 text-xs font-mono font-bold uppercase tracking-widest">
                    <ShieldCheck className="w-4 h-4" />
                    Production ML Lineage Guard & MedGemma Telemetry
                  </div>
                  <h3 className="text-xl font-black text-white mt-1 font-display">
                    Protect MedGemma & Multi-Hospital Clinical AI Models
                  </h3>
                  <p className="text-xs text-stone-400 mt-1">
                    Traces end-to-end ML lineage, monitors real-time epistemic uncertainty and demographic bias telemetry, and blocks silent upstream schema drift.
                  </p>
                </div>

                {/* Expanded MedGemma Telemetry Metrics Strip */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  <div className="bg-stone-950 border border-stone-800 p-3 rounded-2xl font-mono text-xs">
                    <div className="text-stone-400 text-[10px] uppercase font-bold">Epistemic Uncertainty</div>
                    <div className="text-lg font-black text-amber-400 flex items-center justify-between mt-1">
                      <span>{epistemicUncertainty}</span>
                      <span className={`text-[10px] px-1.5 py-0.5 rounded ${epistemicUncertainty < 0.1 ? 'bg-emerald-500/20 text-emerald-400' : 'bg-rose-500/20 text-rose-400'}`}>
                        {epistemicUncertainty < 0.1 ? 'LOW' : 'HIGH RISK'}
                      </span>
                    </div>
                  </div>

                  <div className="bg-stone-950 border border-stone-800 p-3 rounded-2xl font-mono text-xs">
                    <div className="text-stone-400 text-[10px] uppercase font-bold">Demographic Parity Bias</div>
                    <div className="text-lg font-black text-cyan-400 flex items-center justify-between mt-1">
                      <span>{demographicBias}</span>
                      <span className={`text-[10px] px-1.5 py-0.5 rounded ${demographicBias < 0.05 ? 'bg-emerald-500/20 text-emerald-400' : 'bg-rose-500/20 text-rose-400'}`}>
                        {demographicBias < 0.05 ? 'MINIMAL' : 'THRESHOLD EXCEEDED'}
                      </span>
                    </div>
                  </div>

                  <div className="bg-stone-950 border border-stone-800 p-3 rounded-2xl font-mono text-xs">
                    <div className="text-stone-400 text-[10px] uppercase font-bold">Trial Multi-Hospital Hubs</div>
                    <div className="text-lg font-black text-emerald-400 mt-1">
                      3 Active Hospitals
                    </div>
                    <div className="text-[9px] text-stone-400 truncate">Mayo • Hopkins • Charité</div>
                  </div>
                </div>

                {/* Simulation Control */}
                <div className="bg-stone-950 border border-stone-800 p-4 rounded-2xl space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-mono font-bold text-white">Production ML Protection Status</span>
                    {mlDriftSimulated && !mlAlertResolved ? (
                      <span className="px-2.5 py-1 rounded bg-rose-500/20 text-rose-300 text-xs font-mono font-bold border border-rose-500/40 flex items-center gap-1.5">
                        <AlertTriangle className="w-3.5 h-3.5 text-rose-400" />
                        UNCERTAINTY & DRIFT ALERT
                      </span>
                    ) : (
                      <span className="px-2.5 py-1 rounded bg-emerald-500/20 text-emerald-300 text-xs font-mono font-bold border border-emerald-500/40 flex items-center gap-1.5">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                        ML LINEAGE & TELEMETRY HEALTHY
                      </span>
                    )}
                  </div>

                  <p className="text-xs text-stone-400">
                    Target Deployment: <strong className="text-amber-300">medgemma-27b-longevity-diagnostic</strong> receiving features from <strong className="text-amber-300 font-mono">patient_biomarker_features</strong>.
                  </p>

                  <div className="flex items-center gap-3 pt-2">
                    <button
                      onClick={handleSimulateDrift}
                      className="px-4 py-2 rounded-xl bg-rose-600/30 hover:bg-rose-600/50 text-rose-200 border border-rose-500/40 text-xs font-mono font-bold cursor-pointer transition-all"
                    >
                      Trigger Live Drift & Bias Inspection
                    </button>
                    <button
                      onClick={() => handleRunAgentAction('Auto-Fix ML Lineage Drift & Update DataHub')}
                      disabled={isAgentRunning || !mlDriftSimulated}
                      className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-mono font-bold cursor-pointer transition-all disabled:opacity-40"
                    >
                      Run Agent Telemetry Repair
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* AUTOMATED DATA CONTRACT ENFORCEMENT */}
            {activeChallenge === 'data_contracts' && (
              <div className="space-y-5 animate-fadeIn">
                <div className="border-b border-stone-800 pb-4">
                  <div className="flex items-center gap-2 text-cyan-400 text-xs font-mono font-bold uppercase tracking-widest">
                    <CheckSquare className="w-4 h-4" />
                    Automated Data Contract Enforcement
                  </div>
                  <h3 className="text-xl font-black text-white mt-1 font-display">
                    Glossary-Derived JSON Schema & Great Expectations Contracts
                  </h3>
                  <p className="text-xs text-stone-400 mt-1">
                    Agents automatically generate and validate JSON Schema & Great Expectations contract specifications directly from DataHub glossary terms (PHI_Data, VitalSigns, Biomarkers).
                  </p>
                </div>

                <div className="bg-stone-950 border border-stone-800 rounded-2xl p-4 font-mono text-xs relative overflow-hidden">
                  <div className="flex items-center justify-between pb-2 mb-2 border-b border-stone-800 text-stone-400">
                    <span className="flex items-center gap-2">
                      <BookOpen className="w-4 h-4 text-cyan-400" />
                      Generated Data Contract Spec (JSON Schema / Great Expectations)
                    </span>
                    <span className="text-[10px] text-emerald-400 font-bold">Glossary Enforced</span>
                  </div>
                  <pre className="text-cyan-200/90 overflow-x-auto max-h-56 leading-relaxed">
                    {contractSpec}
                  </pre>
                </div>

                <button
                  onClick={() => handleRunAgentAction('Enforce Data Contract & Write Aspect to DataHub')}
                  disabled={isAgentRunning}
                  className="w-full py-3.5 px-6 rounded-2xl bg-cyan-600 hover:bg-cyan-700 text-white font-bold text-sm shadow-xl flex items-center justify-center gap-2 cursor-pointer transition-all disabled:opacity-50"
                >
                  <ShieldCheck className="w-4 h-4" />
                  Emit Verified dataContract Aspect to DataHub GMS
                </button>
              </div>
            )}

            {/* Challenge 4: OPEN / WILDCARD - DR. T CLINICAL & BIO-MARKET */}
            {activeChallenge === 'wildcard_drt' && (
              <div className="space-y-5 animate-fadeIn">
                <div className="border-b border-stone-800 pb-4">
                  <div className="flex items-center gap-2 text-amber-300 text-xs font-mono font-bold uppercase tracking-widest">
                    <Sparkles className="w-4 h-4" />
                    Ecosystem Governance
                  </div>
                  <h3 className="text-xl font-black text-white mt-1 font-display">
                    Dr. T Bio-Market & Interstellar DataHub Governance
                  </h3>
                  <p className="text-xs text-stone-400 mt-1">
                    Integrates Cosmos Green Farm harvest data, Clinical AI biomarker streams, and Dr. T Institute transcripts with DataHub FHIR & Interstellar Data Contracts.
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  <div className="bg-stone-950 p-3.5 rounded-2xl border border-amber-500/30 text-center space-y-1">
                    <Globe className="w-5 h-5 text-amber-400 mx-auto" />
                    <div className="text-xs font-bold text-white font-mono">FHIR R4 Ledger</div>
                    <div className="text-[10px] text-stone-400">DataHub Standardized</div>
                  </div>
                  <div className="bg-stone-950 p-3.5 rounded-2xl border border-amber-500/30 text-center space-y-1">
                    <Tag className="w-5 h-5 text-emerald-400 mx-auto" />
                    <div className="text-xs font-bold text-white font-mono">Cosmos Bio Harvest</div>
                    <div className="text-[10px] text-stone-400">Interstellar Contract</div>
                  </div>
                  <div className="bg-stone-950 p-3.5 rounded-2xl border border-amber-500/30 text-center space-y-1">
                    <ShieldCheck className="w-5 h-5 text-rose-400 mx-auto" />
                    <div className="text-xs font-bold text-white font-mono">HIPAA Zero Trust</div>
                    <div className="text-[10px] text-stone-400">DataHub Assertions</div>
                  </div>
                </div>

                <button
                  onClick={() => handleRunAgentAction('Run Full Dr. T DataHub Governance Sync')}
                  disabled={isAgentRunning}
                  className="w-full py-3.5 px-6 rounded-2xl bg-gradient-to-r from-emerald-600 via-amber-500 to-rose-600 text-white font-bold text-sm shadow-xl flex items-center justify-center gap-2 cursor-pointer transition-all disabled:opacity-50"
                >
                  <Activity className="w-4 h-4" />
                  Synchronize Dr. T Ecosystem with DataHub Catalog
                </button>
              </div>
            )}

            {/* Live DataHub MCP Agent Terminal Output */}
            <div className="bg-stone-950 border border-stone-800 rounded-2xl p-4 space-y-3 font-mono">
              <div className="flex items-center justify-between border-b border-stone-800 pb-2">
                <span className="text-xs text-amber-300 font-bold flex items-center gap-2">
                  <Terminal className="w-4 h-4" />
                  DataHub MCP Agent Execution Console
                </span>
                <span className="text-[10px] text-stone-400">Live Agent Stream</span>
              </div>
              <div className="max-h-40 overflow-y-auto space-y-1.5 text-xs">
                {agentLog.map((log, idx) => (
                  <div key={idx} className="flex items-start gap-2 text-stone-300">
                    <span className="text-[10px] text-stone-500 shrink-0">{log.timestamp}</span>
                    <span className={`font-bold shrink-0 ${
                      log.type === 'error' ? 'text-rose-400' :
                      log.type === 'warning' ? 'text-amber-400' :
                      log.type === 'success' ? 'text-emerald-400' : 'text-blue-400'
                    }`}>
                      [{log.agent}]:
                    </span>
                    <span className="text-stone-300 leading-snug">{log.message}</span>
                  </div>
                ))}
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  );
};

export default DataHubAgentSuite;
